### ISSUE TITLE
Editing server components requires restarting dev server

### ISSUE THREAD

**Issue by rob-gordon** [dai-shi/wakuwork#13]
I can edit the entry point...

```tsx
const App = serve<{ name: string }>("App");
root.render(
  <StrictMode>
    <App name="THIS EDIT WORKS" />
  </StrictMode>
);
```

and I can edit client components

```tsx
export const Counter = () => {
  const [count, setCount] = useState(0);
  return (
    <div style={{ border: "3px blue dashed", margin: "1em", padding: "1em" }}>
      <p>This edit works...</p>
      <p>Count: {count}</p>
    </div>
  );
};
```

but any edits to the server component in `App.tsx` require stopping the dev server and restarting it. Is this the expected behavior?

Using `"wakuwork": "~0.9.0"` on OSX

**Comment by dai-shi** [comment]
Hi, welcome to the Wakuwork world!

Unfortunately, it's not supported yet. There are some challenges.
- We probably need to restart the server (not just re-bundling).
- File based watching is suboptimal and we need module graph for server bundling (which doesn't exist yet).
  - For example, a component can be used for both server and client.

It will hopefully be done, but takes time. Meanwhile, a workaround is to use `nodemon` or some alternatives.

```bash
nodemon wakuwork dev
```
(I never tried though. Does it work?)

---

FYI, I use `--ignore` for files I know are client only.

https://github.com/dai-shi/wakuwork/blob/81da2bdfef4d54e4543264cbd85858c0b9648bc6/package.json#L49

**Comment by rob-gordon** [comment]
`nodemon` works but(!) it opens a new tab on every restart, so in practice it's not much different than manually stopping and restarting the dev server. 

In the short term, maybe it would be better if `devServer.ts` did not auto-open a window (or took an --open config option). That way `nodemon --watch src --ext ts,tsx --exec 'wakuwork dev'` could be used when developing and it would only require a page refresh?

https://github.com/dai-shi/wakuwork/blob/81da2bdfef4d54e4543264cbd85858c0b9648bc6/src/devServer.ts#L39

**Comment by dai-shi** [comment]
Yeah, let's remove open command. That's annoying.
