### ISSUE TITLE
Use import 'server-only' 

### ISSUE THREAD

**Issue by sayjeyhi** [dai-shi/wakuwork#17]
Can we user import `'server-only'` on sensitive files?

like what react demo has:
https://github.com/reactjs/server-components-demo/blob/37f20f98ce21a4ca3f29d66fd77d08e95c6fd003/src/db.js#L10

**Comment by dai-shi** [comment]
Can you experiment if it works as expected?

**Comment by dai-shi** [comment]
server-only is an actual package you need to install, I suppose.

**Comment by sayjeyhi** [comment]
Yes, you are right, installed that package and it worked, do you need me to complete that example with Postgres?

**Comment by dai-shi** [comment]
> it worked

Does it work as expected even if we accidentally import it on the client?

> do you need me to complete that example with Postgres?

Yeah, I would like to see the full example.

I'm not going to merge the PR. Instead, I will create an examples section in README and link to your fork.

**Comment by lubieowoce** [comment]
@sayjeyhi you mentioned "sensitive" files, so i thought I'd mention this. `import "server-only"` won't actually protect anything. it'll throw an error on the client, but if you're worried about leaking secrets (), it's not gonna help.

**Comment by dai-shi** [comment]
> Does it work as expected even if we accidentally import it on the client?

I'm still curious.

@sayjeyhi Can we continue this issue (and maybe #19) or should we close?

**Comment by dai-shi** [comment]
While working on something, I found that `server-only` works (warns) as expected. So, closing.
