### ISSUE TITLE
Use process.env

### ISSUE THREAD

**Issue by sayjeyhi** [dai-shi/wakuwork#18]
I tried to use `pg` package for node postgres and it shows me process undefined, I think somehow there should be a way to pass and allow env variables.

```bash
Uncaught ReferenceError: process is not defined
    at node_modules/pg/lib/defaults.js (defaults.js:8:9)
    at __require (chunk-DFKQJ226.js?v=99f0aa57:8:50)
    at node_modules/pg/lib/utils.js (utils.js:5:18)
    at __require (chunk-DFKQJ226.js?v=99f0aa57:8:50)
    at node_modules/pg/lib/client.js (client.js:4:13)
    at __require (chunk-DFKQJ226.js?v=99f0aa57:8:50)
    at node_modules/pg/lib/index.js (index.js:3:14)
    at __require (chunk-DFKQJ226.js?v=99f0aa57:8:50)
    at index.js:55:1
```

**Comment by sayjeyhi** [comment]
I used vite config file to get env vars.
```js
import { defineConfig, loadEnv } from 'vite'

export default defineConfig(({ command, mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  return {
    define: {
      'process.env': env
    },
  }
})
```

**Comment by dai-shi** [comment]
> for this I had to install vite again and pass it.

I didn't know such a workaround works. Good to know!

Though, does it work? I think `pg` is server-side package.
The reason we don't have `process` is we are using ESM.

**Comment by dai-shi** [comment]
Hm, but we should be able to import cjs from esm…

**Comment by sayjeyhi** [comment]
AFAIK Vite is not allowing me to import cjs, even though I tried to import `react-pg` and it gave me error:
```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-pg.js?v=2de1889c' does not provide an export named 'default' (at db.js:4:8)
```

There is a package called `@originjs/vite-plugin-commonjs` but it didn't help.

**Comment by dai-shi** [comment]
https://github.com/dai-shi/wakuwork/pull/19#discussion_r1159229405
