### ISSUE TITLE
Support server bundling with vite

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/wakuwork#21]
Currently, wakuwork uses `react-server-dom-webpack/node-loader` for handing `"use client"` and `"use server"`.
We use vite for client bundling, but for server bundling we use a naive approach.
It's limited. For example, we now don't support `"use client"` in `node_modules`.

I'm hoping we could use vite for server bundling. Wish [vite-rsc](https://github.com/cyco130/vite-rsc/tree/main/packages/vite-rsc) does that.

@nksaraf What's the current status?

**Comment by dai-shi** [comment]
I will see if I can do it in this repo.

**Comment by hyf0** [comment]
Have you thought through it?

I guess we just need to adapt the [register logic](https://github.com/facebook/react/blob/main/packages/react-server-dom-webpack/src/ReactFlightWebpackNodeRegister.js#L200) in Rollup and apply it for `use client` `components` in `transform` hook.

**Comment by dai-shi** [comment]
Well, I'm learning vite. Will open a PR if something is ready.

**Comment by dai-shi** [comment]
Having a trouble...
